<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        # The space between the buttons
        padding: 50
        spacing: 20



        Button:
            text: "Hello Vero"
        
        Button:
            text: "Goodbye Vero"

        Button:
            text: "Imi place sa mananc"
            pos_hint: {"center_x": 0.5}
            size_hint: (0.5, 0.5)
