<MyLayout>
   
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        # The space between the buttons
        padding: 50
        spacing: 20

        Label:
            text: "Name"
    
        TextInput:
            multiline:False

        Button:
            text: "Submit"

        Image:
            source: "image_kivy.jpg"

            # Image properties in the app
            allow_strech: True
            keep_ratio: False